# CarDekho Used Car Price Prediction Project 2.

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [57]:
df = pd.read_csv("Datasets\car_data_v2.csv")
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\Harshit\AppData\Local\Temp\ipykernel_3668\1796603013.py:1: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv("Datasets\car_data_v2.csv")

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [58]:
df.shape

(4340, 8)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [60]:
df.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [61]:
df.drop("name", axis = 1, inplace = True)

In [62]:
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner

## Data Preprocessing

In [63]:
## Checking missing values
df.isna().sum()

year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [64]:
## Checking duplicates
df[df.duplicated()]

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
13,2007,60000,70000,Petrol,Individual,Manual,First Owner
14,2007,135000,50000,Petrol,Individual,Manual,First Owner
15,2012,600000,100000,Diesel,Individual,Manual,First Owner
16,2017,250000,46000,Petrol,Individual,Manual,First Owner
17,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...
4310,2015,465000,41123,Diesel,Dealer,Manual,First Owner
4311,2017,1900000,20118,Petrol,Dealer,Automatic,First Owner
4319,2012,400000,70000,Diesel,Individual,Manual,First Owner
4322,2013,500000,120000,Diesel,Individual,Manual,First Owner
4336,2014,409999,80000,Diesel,Individual,Manual,Second Owner

In [65]:
df.drop_duplicates(inplace=True)

In [66]:
df.shape

(3498, 7)

In [67]:
## Encoding categorical columns

In [68]:
X = df.drop("selling_price", axis = 1)
y = df["selling_price"]

In [69]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [70]:
ohe_cols = df.select_dtypes(include = "object").columns
ohe_cols

Index(['fuel', 'seller_type', 'transmission', 'owner'], dtype='object')

In [73]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
ohe_encoder = OneHotEncoder(sparse_output=False)

X_train_ohe_arr = ohe_encoder.fit_transform(X_train[ohe_cols])
X_test_ohe_arr = ohe_encoder.transform(X_test[ohe_cols])

In [74]:
X_train_ohe_df = pd.DataFrame(X_train_ohe_arr, columns=ohe_encoder.get_feature_names_out(ohe_cols), index = X_train.index)

In [75]:
X_train_ohe_df.head()

,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
3376,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
244,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1256,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2030,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2129,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

In [76]:
X_train = pd.concat([X_train, X_train_ohe_df], axis = 1)

In [77]:
X_train.head()

,year,km_driven,fuel,seller_type,transmission,owner,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,...,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
3376,2013,71000,Diesel,Dealer,Manual,First Owner,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
244,2014,70000,Diesel,Individual,Manual,First Owner,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1256,2007,84000,Petrol,Individual,Manual,Second Owner,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2030,2008,144000,Diesel,Individual,Manual,Third Owner,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2129,2020,1100,Petrol,Dealer,Manual,First Owner,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

In [78]:
X_train.drop(ohe_cols, axis = 1, inplace = True)

In [79]:
X_test_ohe_df = pd.DataFrame(X_test_ohe_arr, columns=ohe_encoder.get_feature_names_out(ohe_cols), index = X_test.index)
X_test = pd.concat([X_test, X_test_ohe_df], axis = 1)
X_test.drop(ohe_cols, axis = 1, inplace = True)

In [80]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1050 entries, 1855 to 1542
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   year                          1050 non-null   int64
 1   km_driven                     1050 non-null   int64
 2   fuel_CNG                      1050 non-null   float64
 3   fuel_Diesel                   1050 non-null   float64
 4   fuel_Electric                 1050 non-null   float64
 5   fuel_LPG                      1050 non-null   float64
 6   fuel_Petrol                   1050 non-null   float64
 7   seller_type_Dealer            1050 non-null   float64
 8   seller_type_Individual        1050 non-null   float64
 9   seller_type_Trustmark Dealer  1050 non-null   float64
 10  transmission_Automatic        1050 non-null   float64
 11  transmission_Manual           1050 non-null   float64
 12  owner_First Owner             1050 non-null   float64
 13  owner_Fourth & Above Owner    1050 non-null   float64
 14  owner_Second Owner            1050 non-null   float64
 15  owner_Test Drive Car          1050 non-null   float64
 16  owner_Third Owner             1050 non-null   float64
dtypes: float64(15), int64(2)
memory usage: 147.7 KB

In [81]:
## Applying Standardization
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Model Creation

In [82]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

from sklearn.metrics import r2_score

In [83]:
models = {
    "LinearRegression" : LinearRegression(),
    "lasso" : Lasso(),
    "ridge" : Ridge(),
    "svm" : SVR(),
    "KNN" : KNeighborsRegressor(),
    "DecisionTree" : DecisionTreeRegressor(), 
    "RandomForest" : RandomForestRegressor(), 
    "Adaboost" : AdaBoostRegressor(), 
    "gradient" : GradientBoostingRegressor(), 
    "xgboost" : XGBRegressor()
}
models

{'LinearRegression': LinearRegression(),
 'lasso': Lasso(),
 'ridge': Ridge(),
 'svm': SVR(),
 'KNN': KNeighborsRegressor(),
 'DecisionTree': DecisionTreeRegressor(),
 'RandomForest': RandomForestRegressor(),
 'Adaboost': AdaBoostRegressor(),
 'gradient': GradientBoostingRegressor(),
 'xgboost': XGBRegressor(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)}

In [ ]:
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train_scaled, y_train)
    y_pred_train = model.predict(X_train_scaled)
    y_pred_test = model.predict(X_test_scaled)

    print(f"{list(models.keys())[i]} train accuracy : {r2_score(y_train, y_pred_train) * 100}")
    print(f"{list(models.keys())[i]} test accuracy : {r2_score(y_test, y_pred_test) * 100}")
    print("-" * 30)

LinearRegression train accuracy : 44.83681945952709
LinearRegression test accuracy : 41.22443058865961
------------------------------
lasso train accuracy : 44.83681945494008
lasso test accuracy : 41.224379938292266
------------------------------
ridge train accuracy : 44.83681706368658
ridge test accuracy : 41.22292223161696
------------------------------

C:\Users\Harshit\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.388e+11, tolerance: 5.842e+10
  model = cd_fast.enet_coordinate_descent(

svm train accuracy : -6.026007813483858
svm test accuracy : -5.841296025913034
------------------------------
KNN train accuracy : 62.92249530195585
KNN test accuracy : 47.126158143951415
------------------------------
DecisionTree train accuracy : 95.38203331759433
DecisionTree test accuracy : 15.404825331844474
------------------------------
RandomForest train accuracy : 87.64673910251078
RandomForest test accuracy : 40.111034581118076
------------------------------
Adaboost train accuracy : 32.23525906315623
Adaboost test accuracy : 27.615676569991997
------------------------------